line-length = 88
target-version = "py312"

[lint]
select = [
    "E", "W", "F", "I", "N", "UP", "B", "S", "A", "PL", "TCH", "RUF"
]
ignore = [
    "E501" # Line too long
]

[lint.isort]
known-first-party = ["app"]
